# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d84ff6b35dec6d2e2763791b104cdc4ee68721f33c3dccc191d9f5c540c9e559492e3a1a5eaeef07923314bfe5003547dbdef9b42ea871900bdac2f8ba201f4

test:
  secret_key_base: 5498ad5a943bb259a289d1edde26c4dbfc4290123cba3496ee9a6c4cf8c25ab3e2f342e64afce70847bccc7cd17bdd078f6d297e2bf5689a574b57d4252c5e14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
